---
- hosts: localhost
  strategy: debug
  tasks:
    - name: install python2-zabbix-api
      yum:
            name: python2-zabbix-api
            state: present
    - name: Source variables and password
      shell: source /trinity/local/trinity.shadow && echo $ZABBIX_ADMIN_PASSWORD
      register: ZABBIX_ADMIN_PASSWORD

    - name: Source variables and password
      shell: source /etc/trinity.sh && echo $TRIX_CTRL_IP
      register: TRIX_CTRL_IP


    - name: Test myzabbix 
      myzabbix: 
          username: "Admin"
          password: "{{ ZABBIX_ADMIN_PASSWORD.stdout  }}"
          hostname: "{{ TRIX_CTRL_IP.stdout  }}"
          object:   "{{item.object}}"
          action:   "{{item.action}}"
          query:    "{{item.query}}"
          params:   "{{item.params}}"
      with_items:
          - {object: "mediatype", action: "get", query: { }, params: { } }
          - {object: "mediatype", action: "find_update", query: { name: "Local e-mail" } , params: { smtp_server: "127.0.0.1" } }
          - object: "action"
            action: "find_update"
            query: 
                 name: "Auto registration"
            params:  
                 operations:
                     - actionid: 7
                       operationid: 13
                       operationtype: 6
                       optemplate: 
                          - operationid: 13
                            templateid: 10129
                          - operationid: 13
                            templateid: 10104
                       recovery: 0 
